<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShippingApp.Models\ShippingApp.Models.csproj" />
    <ProjectReference Include="..\ShippingApp.Data\ShippingApp.Data.csproj" />
  </ItemGroup>
</Project>
